-- Sports Field Booking System
-- Run this entire file in Supabase -> SQL Editor

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  phone text,
  role text not null default 'customer' check (role in ('customer','receptionist','manager')),
  created_at timestamptz not null default now()
);

create table if not exists public.sports_fields (
  field_id bigint generated by default as identity primary key,
  field_name text not null,
  field_type text not null,
  location text not null,
  price numeric(10,2) not null check (price >= 0),
  image_url text,
  status text not null default 'Available' check (status in ('Available','Unavailable'))
);

create table if not exists public.bookings (
  booking_id bigint generated by default as identity primary key,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  field_id bigint not null references public.sports_fields(field_id),
  booking_date date not null,
  start_time time not null,
  end_time time not null,
  booking_status text not null default 'Pending' check (booking_status in ('Pending','Confirmed','Cancelled')),
  created_at timestamptz not null default now(),
  constraint valid_booking_time check (end_time > start_time)
);

create table if not exists public.payments (
  payment_id bigint generated by default as identity primary key,
  booking_id bigint not null unique references public.bookings(booking_id) on delete cascade,
  payment_date date not null default current_date,
  amount numeric(10,2) not null check (amount >= 0),
  payment_method text not null,
  payment_status text not null default 'Pending' check (payment_status in ('Pending','Paid','Failed'))
);

-- Prevent double-booking for the same field/date/time.
create or replace function public.check_booking_overlap()
returns trigger language plpgsql as $$
begin
  if new.booking_status <> 'Cancelled' and exists (
    select 1 from public.bookings b
    where b.field_id = new.field_id
      and b.booking_date = new.booking_date
      and b.booking_status <> 'Cancelled'
      and b.booking_id <> coalesce(new.booking_id,0)
      and new.start_time < b.end_time
      and new.end_time > b.start_time
  ) then
    raise exception 'FIELD_TIME_ALREADY_BOOKED';
  end if;
  return new;
end $$;

drop trigger if exists trg_check_booking_overlap on public.bookings;
create trigger trg_check_booking_overlap
before insert or update on public.bookings
for each row execute function public.check_booking_overlap();

-- Automatically create a profile after signup.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id,full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email,'@',1)));
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Seed only the four fields shown in the supplied UI.
insert into public.sports_fields(field_name,field_type,location,price,image_url)
select * from (values
('ملعب كرة القدم','خارجي','الملعب الرئيسي',40,'assets/football.jpg'),
('ملعب كرة السلة','داخلي','صالة 1',20,'assets/basketball.jpg'),
('ملعب التنس','خارجي','الملعب الجانبي',25,'assets/tennis.jpg'),
('ملعب الكرة الطائرة','داخلي','صالة 2',15,'assets/volleyball.jpg')
) as v(field_name,field_type,location,price,image_url)
where not exists (select 1 from public.sports_fields);

-- RLS
alter table public.profiles enable row level security;
alter table public.sports_fields enable row level security;
alter table public.bookings enable row level security;
alter table public.payments enable row level security;

drop policy if exists "profiles own select" on public.profiles;
create policy "profiles own select" on public.profiles for select to authenticated using (id=auth.uid());

drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles for update to authenticated using (id=auth.uid());

drop policy if exists "fields authenticated read" on public.sports_fields;
create policy "fields authenticated read" on public.sports_fields for select to authenticated using (true);

drop policy if exists "bookings own read" on public.bookings;
create policy "bookings own read" on public.bookings for select to authenticated using (customer_id=auth.uid());

drop policy if exists "bookings own insert" on public.bookings;
create policy "bookings own insert" on public.bookings for insert to authenticated with check (customer_id=auth.uid());

drop policy if exists "bookings own update" on public.bookings;
create policy "bookings own update" on public.bookings for update to authenticated using (customer_id=auth.uid()) with check (customer_id=auth.uid());

drop policy if exists "payments own read" on public.payments;
create policy "payments own read" on public.payments for select to authenticated
using (exists(select 1 from public.bookings b where b.booking_id=payments.booking_id and b.customer_id=auth.uid()));

drop policy if exists "payments own insert" on public.payments;
create policy "payments own insert" on public.payments for insert to authenticated
with check (exists(select 1 from public.bookings b where b.booking_id=payments.booking_id and b.customer_id=auth.uid()));

-- Manager/receptionist policies can be added later when roles are needed.
